import styles from '../styles/Category.module.css';
import Link from 'next/link';
import Image from 'next/image';
import Navbar from '../components/navbar';
import Head from 'next/head';
import Topbar from '../components/topbar';
import { useRouter } from 'next/router';
import { useState } from 'react';
import parentInfo from '../data/categoryName';

export default function Category() {
  const router = useRouter();
  const { name } = router.query;

  const decodedName = decodeURIComponent(name);

  const greeting = `Hello, ${decodedName}`;

  const [selectedData, setSelectedData] = useState(null);

  const handleItemClick = (item) => {
    setSelectedData(item);
    router.push({
      pathname: '/symptoms',
      query: { selectedData: JSON.stringify(item), name: encodeURIComponent(decodedName) },
    });
  };

  return (
    <>
      <Head>
        <title>Meddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>

      <div className={styles.body_main}>
        <main className={styles.main}>
          <div className={styles.overlayButton}>
            <Topbar />
          </div>

          <div>
            <h1>{greeting}</h1>
            <p className={styles.categoryPage_question}>Where are you experiencing discomfort today?</p>
          </div>

          <section className={styles.category_buttons}>
            {parentInfo.map((item) => (
              <div key={item.id} onClick={() => handleItemClick(item)}>
                <div>
                  <section className={styles.button_shape}>
                    <div>
                      <button className={styles.category_button}>
                        <div className={styles.category_button_inside}>
                          <div className={styles.body_icons}>
                            <Image src={item.image} alt="" width={60} height={60} />
                          </div>
                          <div className={styles.category_button_texts}>
                            <p className={styles.category_head}>{item.category}</p>
                            <p className={styles.category_symptoms}>{item.symptomsTwo}</p>
                            <p className={styles.category_symptoms}>{item.symptomsThree}</p>
                          </div>
                        </div>
                      </button>
                    </div>
                  </section>
                </div>
              </div>
            ))}
          </section>
        </main>

        <div className={styles.navbar}>
          <Navbar />
        </div>
      </div>
    </>
  );
}
