import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/EnterName.module.css'
import Navbar from '../components/navbar/index.js';
import Link from 'next/link'
import { useState } from 'react';
import Category from './Category';
import Survey from '../components/enterText/Survey';
import Topbar from '../components/topbar';

export default function EnterTheirName() {

  return (
    <>

      <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
      <div className={styles.body_main}>
      <main className={styles.main}>
      
      <div className={styles.overlayButton}>
        <Topbar/>
        </div>
       
       <div style={{display: isActiveOne ? 'block' : 'none'}}>

</div>


       <h1 className={styles.enter_yourname_header}>Enter Their Details Here:</h1>
       <Survey/>
       <div className={styles.enteryourpage__begin_button_div}>
       <Link href="/Category">
        <button className={styles.enteryourpage__begin_button} onClick="">Begin!!</button>
       </Link>
       </div>
      </main>
      <div className={styles.navbar}>
      <Navbar/>
      </div>
      </div>
    </>
  )
}
