import Head from 'next/head';
import styles from '../styles/EnterName.module.css';
import Navbar from '../components/navbar/index.js';
import Link from 'next/link';
import Topbar from '../components/topbar';
import { useRouter } from 'next/router';
import { useState } from 'react';

export default function EnterYourName() {
  const router = useRouter();
  const [name, setName] = useState('');

  const handleSubmit = (event) => {
    event.preventDefault();
    const encodedName = encodeURIComponent(name);
    router.push(`/Category?name=${encodedName}`);
  };

  const handleNameChange = (event) => {
    setName(event.target.value);
  };

  return (
    <>
      <Head>
        <title>Meddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
      <div className={styles.body_main}>
        <main className={styles.main}>
          <div className={styles.overlayButton}>
            <Topbar />
          </div>

          <h1 className={styles.enter_yourname_header}>Enter Your Details Here:</h1>

          <form onSubmit={handleSubmit}>
            <p className={styles.label}>Name:</p>
            <div className={styles.spaceholder_first_name}>
              <input
                className={styles.input_name}
                type="text"
                id="name"
                name="name"
                value={name}
                onChange={handleNameChange}
                maxLength={10}
              />
            </div>
          </form>

          <form>
            <div className={styles.enteryourpage__begin_button_div}>
              <Link href={`/Category?name=${encodeURIComponent(name)}`}>
                <button className={styles.enteryourpage__begin_button}>Begin!!</button>
              </Link>
            </div>
          </form>
        </main>
        <div className={styles.navbar}>
          <Navbar />
        </div>
      </div>
    </>
  );
}
