import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Identify.module.css'
import Navbar from '../components/navbar/index.js';
import Link from 'next/link'


export default function Identify() {


  return (
    <>

        <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>

<div className={styles.body_main}>
      <main className={styles.main}>

       <h1 className={styles.patient_choices_header}>Who are you Checkup For?</h1>


<section className={styles.patient_choices_buttons}>
        <Link href="/EnterYou">
        <button className={styles.patient_choices_myself} onclick="">
        <Image
                src = "/icons/mySelfBear.svg"
                alt =""
                width = {69}
                height = {104}
        />Myself
        </button>
       </Link>




       <Link href="/EnterTheir">
        <button className={styles.patient_choices_someoneelse} onclick="">
        <Image
                src = "/icons/someoneElseBear.svg"
                alt =""
                width = {92}
                height = {81}
        />Someone Else</button>
       </Link>

       </section>
       <Navbar/>
      </main>
      </div>
    </>
  )
}
