import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Identify.module.css'
import Navbar from '../components/navbar/index.js';
import Link from 'next/link'


export default function Identify() {


  return (
    <>
        <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>

<div className={styles.body_main}>
      <main className={styles.main}>
      <div className={styles.overlayButton}>
          <Image
           src = "/icons/overlayButton.png"
           alt =""
           width = {60}
           height = {60}
           />
        </div>
        <div className={styles.welcome_page_texts}>
       <h1 className={styles.patient_choices_header}>Who is this Checkup for?</h1>
        <section className={styles.patient_choices_buttons}>
        <Link href="/EnterYou" className={styles.yourself}>
        <button className={styles.patient_choices_myself} onclick="">
        <Image
                src = "/icons/mySelfBear.svg"
                alt =""
                width = {69}
                height = {104}
        />
        <h1>Myself</h1>
        </button>
       </Link>
       <Link href="/EnterTheir" className={styles.someoneelse}>
        <button className={styles.patient_choices_someoneelse} onclick="">
        <Image
                src = "/icons/someoneElseBear.svg"
                alt =""
                width = {92}
                height = {81}
        />
        <h1>Someone else</h1>
        </button>
       </Link>
       </section>
       </div>

      </main>

      <div className={styles.navbar}>
      <Navbar/>
      </div>
      </div>
    </>
  )
}
