import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/index.js';
import Link from 'next/link'


export default function Welcome() {
  return (
    <>
      <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={styles.main}>

        <Image
        src = "/icons/logo.png"
        alt =""
        width = {200}
        height = {200}
        />

       <div
       className={styles.welcome_page__texts}>
       <h1
       className={styles.welcome_page_header}>Welcome to Meddy</h1>
       <p
       className={styles.welcome_page_slogan}>Meddy provides you with a fast assessment of your current symptoms you may be feeling</p>
       </div>

       <div
       className={styles.welcome_page_button_section}>
       <Link href="/Startpage">
        <button className={styles.welcome_page_button} onclick="">Begin!!</button>
       </Link>
       </div>
      </main>
    </>
  )
}
