import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/index.js';

const inter = Inter({ subsets: ['latin'] })

export default function disclaimer() {
  return (
    <>
      <Head>
        <title> Disclaimer </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Image
        />


        <div>
        <h3>Take a short assessment</h3>
        <h3>To Find out results for:</h3>
        <h3> --Possible causes of symptoms</h3>
        <h3> -- Recommendations on what tot</h3>  
        <h3>do next, medication or reach out for assistance.</h3>
        </div>


       <button 
       href=""
       className={styles.understand_button}>I understand</button>
      </main>
    </>
  )
}
