import styles from '../styles/Quiz.module.css'
import Head from 'next/head'
import Topbar from '../components/topbar'
import Navbar from '../components/navbar'


export default function QuizCorrect(){

    return(
        <>
        <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
        </Head>

        <div className={styles.body_main}>
            <main className={styles.main}>
                <div className={styles.overlayButton}>
                    <Topbar/>
                </div>
                
                <h1>Incorrect</h1>
                <h1> I want it to be a pop up, and have a button that says try again, displays for 5 seconds.</h1>
                    
            </main>
            <div className={styles.navbar}>
                <Navbar/>
            </div>
        </div>
        </>
    )

}