import styles from '../styles/Quiz.module.css'
import Head from 'next/head'
import Topbar from '../components/topbar'
import Navbar from '../components/navbar'
import Link from 'next/link'
export default function Quiz(){

    return(
        <>
        <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
        </Head>

        <div className={styles.body_main}>
            <main className={styles.main}>

        <div className={styles.overlayButton}>
        <Topbar/>
        </div>
        

        <h1>Lets check your knowledge! </h1>

        <Link href="">
        <button></button>
        </Link>
            </main>

            <div className={styles.navbar}>
                <Navbar/>
            </div>
        </div>
        </>
    )

}