import styles from '../styles/References.module.css'
import Link from 'next/link'
import Navbar from '../components/navbar/index.js';
import Head from 'next/head'
import Image from 'next/image';


export default function References() {



    return (
    <>
    <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
 

<div className={styles.body_main}>
    <main className={styles.main}>

    <Image
           src = "/icons/overlayButton.png"
           alt =""
           width = {60}
           height = {60}
           />


    <h1 className={styles.references_title}>References</h1>
    <p className={styles.references_description}>Quick links to the primary medication for each category:</p>


<section className={styles.reference_lists}>
    <section className={styles.references_section}>

        <div className={styles.references_section_content}>
      <Image
            src = "/icons/eyesIcon.svg"
            alt =""
            width = {87}
            height = {24}
      />

      <h1 className={styles.medication_title}>Eye Medication</h1>
         </div>

      <Link className={styles.medication_link} href="https://medlineplus.gov/druginfo/meds/a682159.html#:~:text=Nonprescription%20ibuprofen%20is%20used%20to,class%20of%20medications%20called%20NSAIDs">Learn More</Link>
    </section>


    <section className={styles.references_section}>

    <div className={styles.references_section_content}>
      <Image
            src = "/icons/headIcon.svg"
            alt =""
            width = {60}
            height = {60}
      />

      <h1 className={styles.medication_title}>Head Medication</h1>
      </div>


      <Link className={styles.medication_link} href="https://medlineplus.gov/druginfo/meds/a682159.html#:~:text=Nonprescription%20ibuprofen%20is%20used%20to,class%20of%20medications%20called%20NSAIDs">Learn More</Link>
    </section>

      

                 
  

        
                 </div>

   <div className={styles.navbar}>
   <Navbar/>
   </div>

   </div>
    </>

    
    )
}