import Head from 'next/head'
import styles from '../styles/References.module.css'
import Link from 'next/link'
import Navbar from '../components/navbar'
import Image from 'next/image'


export default function References() {
    return (
        <>

        <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>


      <div className={styles.body_main}>
            <main className={styles.main}>

                <div className={styles.overlayButton}>
                    <Image
                        src="/icons/overlayButton.svg"
                        alt=""
                        width={60}
                        height={60}
                    />
                </div>


                <div>
                    <h1 className={styles.referencepage_header}>References</h1>
                    <p className={styles.referencepage_description}>Quick links to the primary medication for each category:</p>

      

                 
  

        
                 </div>

            </main>

            <div className={styles.navbar}>
                    <Navbar/>
                 </div>

            </div>

  
        </>
    )
}