import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Results.module.css'
import Navbar from '../components/navbar/index.js';
import Link from 'next/link'
import Topbar from '../components/topbar';
import { useRouter } from 'next/router';


export default function ResultsPage() {
  const router = useRouter();
  const { greeting } = router.query;

  return (
    <>
      <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
      <div className={styles.body_main}>
        <main className={styles.main}>
        <div className={styles.overlayButton}>
        <Topbar/>
        </div>
       <h1 className={styles.enter_header}>{greeting}</h1>
       <h2 className={styles.label}>We recommend you take these over the counter drugs for:</h2>
       <div>
          <div className={styles.title_header}>
            <div className={styles.title_Container}>
                <div className={styles.imageCaption} >
                <Image
                    src = "/icons/noseIcon.svg"
                    alt =""
                    width = {60}
                    height = {60}
                />
                <h3>Nose</h3>
                </div>

                <Image
                    src = "/icons/Antitussives.png"
                    alt =""
                    width = {120}
                    height = {120}
                />

            </div>
          </div>
          <div className={styles.infoButtons}>
              <div className={styles.input_name} >
                <p>Medicine Name: </p>
                <h5>Antitussives</h5>
              </div>

              <div className={styles.input_name} >
                <p>Usage:</p>
                <h5>5 to 15 mg every two to four hours, as needed.</h5>
              </div>

              <div className={styles.input_name} >
                <p>Doses:</p>
                <h5>Follow  the directions on the label.</h5>
              </div>

              <div className={styles.input_name} >
              <p>Serious: </p>
                <h5>For more serious conditions,  please seek professional medical assistance</h5>
              </div>
          </div>
      </div>

      <div className={styles.healthyButtons}>
      <form>
        <div className={styles.enteryourpage_submit_button_div}>
          <Link href="/AccessNose">
            <button className={styles.enteryourpage_submit_button}>Access Medication</button>
          </Link>
        </div>
      </form>
      </div>

    </main>
      <div className={styles.navbar}>
      <Navbar/>
      </div>
      </div>
    </>
  )
}
