import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Startpage.module.css'
import Navbar from '../components/navbar/index.js';
import Link from 'next/link'
import React from 'react';
import { useState } from 'react';



export default function Startpage() {

  const[popup, setPop] = useState(false);
  const handleClickOpen = () => {
    setPop(!popup);
  }

  const closePopup = () => {
    setPop(false);
  }

  return (

    <>
    <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
      
    <div className={styles.body_main}>
      <main className={styles.main}>


      <div className={styles.overlayButton}>
          <Image
           src = "/icons/overlayButton.png"
           alt =""
           width = {60}
           height = {60}
           />
        </div>

        
        <div className={styles.main_image}>
        <Image
        src = "/icons/startpageBear.svg"
        alt =""
        width = {119}
        height = {219}
        />
        </div>
        <div>
          <h1 className={styles.intro_page_header}>Check your Symptoms</h1>
        <h2 className={styles.intro_page_description}>Take a short assessment to get results for:</h2>
        <ul className={styles.intro_page_list}> 
          <li>Symptoms</li>
          <li>Recommendations for treatments</li>
          <li>Medications</li>
          <li>Tips to keep your body healthy</li>
        </ul>
        </div>


<div className={styles.intro_page_buttons}>
      <Link href="/">
        <button className={styles.intro_button} onclick="">Decline</button>
       </Link>

        <button onClick={handleClickOpen}
        className={styles.intro_button}>Start</button>

       </div>
       

      <div>
        {popup?
        <div className={styles.popup_main}>
          <div className={styles.popup_alart}>
            <div className={styles.popup_alart_texts}>
             <h1 className={styles.terms_of_services}>Terms of Service</h1>

                <div className={styles.popup_alart_whitepart}>

                  <div  className={styles.popup_alart_inside_texts}>
              <h1 className={styles.popup_alart_lists}>Caution: We are not doctors</h1>
              <li className={styles.popup_alart_lists}>The information displayed on this website are only recommendations for common over the counter drugs.</li>
              <li className={styles.popup_alart_lists}>Information displayed are based on the labels from the specific medication.</li>
              <li className={styles.popup_alart_lists}>We advise users to consult a medical professional or healthcare provider if they’re seeking medical advice, diagnoses, or treatment.</li>
                  </div>

           <div className={styles.popup_alart_close}>
            <h1 onClick = {closePopup}>X</h1>
                 </div>
            </div>
          </div>

          </div>
        </div>: ""}
      </div>

      </main>
    </div>

   </>
  )
}
