import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Startpage.module.css'
import Link from 'next/link'
import React from 'react';
import { useState } from 'react';



export default function Startpage() {

  const[popup, setPop] = useState(false);

  const handleClickOpen = () => {
    setPop(!popup);
  };


  const [isChecked, setIsChecked] = useState(false);

  const handleCheckboxChange = (event) => {
    setIsChecked(event.target.checked);
  };
  return (

    <>
    <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
      
    <div className={styles.body_main}>
      <main className={styles.main}>

     

        <div className={styles.main_image}>
        <Image
        src = "/icons/startpageBear.svg"
        alt =""
        width = {119}
        height = {219}
        />
        </div>
        <div>
          <h1 className={styles.intro_page_header}>Check your Symptoms</h1>
        <h2 className={styles.intro_page_description}>Take a short assessment to get results for:</h2>
        <ul className={styles.intro_page_list}> 
          <li>Possible Symptoms</li>
          <li>Recommended treatment from current sources</li>
          <li>Recommended over the counter medications to take</li>
          <li>Tips to reduce the chances for common symptoms such as headaches</li>
        </ul>
        </div>
      <div className={styles.intro_page_buttons}>
        <button onClick={handleClickOpen} className={styles.intro_button}>Start</button>
       </div>

      <div>
        {popup?
        <div className={styles.popup_main}>
          <div className={styles.popup_alert}>
            <div className={styles.popup_alert_texts}>
             <h1 className={styles.terms_of_services}>Terms of Service</h1>
              <div className={styles.popup_alert_inner_container}>
                <div  className={styles.popup_alert_inside_texts}>
                <h1 className={styles.popup_alert_lists}>Caution: We are not doctors</h1>
                <li className={styles.popup_alert_lists}>The information displayed on this website are only recommendations for common over the counter drugs.</li>
                <li className={styles.popup_alert_lists}>Information displayed are based on the labels from the current common drug store medication.</li>
                <li className={styles.popup_alert_lists}>We advise users to consult a medical professional or healthcare provider if they are seeking medical advice, diagnoses, or treatment.</li>
                <li className={styles.popup_alert_lists}>THESE ARE NOT PRESCRIPTIONS. THEY ARE ONLY PRESCREENING RECOMMENDATIONS. CONSULT A DOCTOR FOR PRESCRIPTIONS</li>
                <li className={styles.popup_alert_lists}>WE ARE NOT LIABLE FOR RISK OR ISSUES ASSOCIATED WITH USING OR ACTING UPON THE INFORMATION ON THIS SITE.</li>
                <div className={styles.intro_button_container}>

              <label className={styles.accept_term_checkbox}>
              <input type="checkbox" checked={isChecked} onChange={handleCheckboxChange} /> <b>I accept Terms of Service</b>
              </label>
              
              {!isChecked}

            <div className={styles.popup_button_container}>
              <Link href="/">
              <button className={styles.intro_button} onclick="">Decline</button>
              </Link>

              {isChecked ? (
              <Link href="/Identify">
                <button className={styles.intro_button}>Start</button>
              </Link>
                ) : (
                  <button disabled className={styles.intro_button_fake}></button>
                ) }
            
            </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>: ""}
  </div>
      </main>
    </div>
   </>
  )
}
