import styles from '../styles/Store.module.css'
import Link from 'next/link'
import Navbar from '../components/navbar/index.js';
import Head from 'next/head'
import Image from 'next/image';
import { useState } from 'react';


export default function Store() {

const [location, setLocation] = useState (false);
const [inputValue, setInputValue] = useState('');
const locationClicked = () => {
        setLocation(!location);
};

    return (
    <>
    <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
 

<div className={styles.body_main}>
    <main className={styles.main}>

    <Image
           onClick={() => setLocation(true)}
           src = "/icons/overlayButton.png"
           alt =""
           width = {60}
           height = {60}
           />

    <h1>Hello,</h1>
    <p className={styles.store_page_description}>Your medication can be access through these stores:</p>
    
    <div className={styles.store_page_location}>

     <img className={styles.location_picture} src="/icons/location.png" onClick={() => {
        if(location){
                setInputValue("");
        }else{
                setInputValue("3700 Willingdon Avenue Burnaby, BC V5G 3H2");
                setTimeout(() => {
                  setLocation(true);
                }, 5000);
        }
        locationClicked();
     }}/>

     <input className={styles.store_page_input} type="text" value={inputValue} onChange={(a) => setInputValue(a.target.value)}/>
    </div>

    {location && (
        <>
        
        <section className={styles.store_list}>

        <section className={styles.store1}>
          <h1 className={styles.store1_name}>London Drugs</h1>
          <p className={styles.store1_adress}>4567 Logheed Hwy.</p>
          <p className={styles.store1_adress}>Burnaby, British Columbia V5C 3Z6</p>

          <a className={styles.stores_phoneNumber}
           href="tel: +16044484856">(604) 448 - 4856</a>

       <section className={styles.stores_buttons}>
        <Link href="https://www.londondrugs.com/">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/place/London+Drugs/@49.2808265,-123.0224954,14z/data=!4m10!1m2!2m1!1sdrugstore!3m6!1s0x548677310104a915:0x8343c870d1b9f478!8m2!3d49.2687065!4d-122.9997164!15sCglkcnVnc3RvcmVaCyIJZHJ1Z3N0b3JlkgEIcGhhcm1hY3maASNDaFpEU1VoTk1HOW5TMFZKUTBGblNVTkNibVpUYmxobkVBReABAA!16s%2Fg%2F1tlc7s2c">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    <section className={styles.store1}>
          <h1 className={styles.store1_name}>Shoppers Drug Mart</h1>
          <p className={styles.store1_adress}>4827 Kingsway</p>
          <p className={styles.store1_adress}>Burnaby, British Columbia V5H 4T6</p>

          <a className={styles.stores_phoneNumber}
           href="tel: +16044332721">(604) 433 - 2721</a>

       <section className={styles.stores_buttons}>
        <Link href="https://www.shoppersdrugmart.ca/en/home?province=ON/">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/place/Shoppers+Drug+Mart/@49.2263507,-123.009612,15z/data=!3m1!5s0x5486765993afd3b3:0xdf91ad7f62f643b8!4m15!1m8!3m7!1s0x5486765992133eb9:0x3b3cf6ad99b77172!2s4827+Kingsway,+Burnaby,+BC+V5H+4T6!3b1!8m2!3d49.2276544!4d-122.9957503!16s%2Fg%2F11nntq80tc!3m5!1s0x548676f641f92629:0x79a717446476c5c4!8m2!3d49.22751!4d-122.995949!16s%2Fg%2F1tnsrmbj">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    <section className={styles.store1}>
          <h1 className={styles.store1_name}>Rexall</h1>
          <p className={styles.store1_adress}>6200 McKey Avenue Unit 140</p>
          <p className={styles.store1_adress}>Burnaby, British Columbia V5H 4L7</p>

          <a className={styles.stores_phoneNumber}
           href="tel: +16044484856">(604) 448 - 4856</a>

       <section className={styles.stores_buttons}>
        <Link href="https://www.londondrugs.com/">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/place/London+Drugs/@49.2808265,-123.0224954,14z/data=!4m10!1m2!2m1!1sdrugstore!3m6!1s0x548677310104a915:0x8343c870d1b9f478!8m2!3d49.2687065!4d-122.9997164!15sCglkcnVnc3RvcmVaCyIJZHJ1Z3N0b3JlkgEIcGhhcm1hY3maASNDaFpEU1VoTk1HOW5TMFZKUTBGblNVTkNibVpUYmxobkVBReABAA!16s%2Fg%2F1tlc7s2c">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    <section className={styles.store1}>
          <h1 className={styles.store1_name}>Grace Pharmacy</h1>
          <p className={styles.store1_adress}>3835 Sunset St.</p>
          <p className={styles.store1_adress}>Burnaby, British Columbia V5G 1T4</p>

          <a className={styles.stores_phoneNumber}
           href="tel: +16044341722">(604) 434 - 1722</a>

       <section className={styles.stores_buttons}>
        <Link href="https://www.guardian-ida-remedysrx.ca/en/british-columbia/burnaby/grace-pharmacy-7044692">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/place/Guardian+-+Grace+Pharmacy/@49.2499025,-123.0290687,15z/data=!3m2!4b1!5s0x548676dd19e1568d:0xa5825579330f9190!4m6!3m5!1s0x54867723c64e1d8b:0x3ae77ecbe973c3bb!8m2!3d49.249889!4d-123.018769!16s%2Fg%2F11h69v7c15">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    <section className={styles.store1}>
          <h1 className={styles.store1_name}>The Medicine Shoppe Pharmacy</h1>
          <p className={styles.store1_adress}>4277 Kingsway M41</p>
          <p className={styles.store1_adress}>Burnaby, British Columbia V5H 3Z2</p>

          <a className={styles.stores_phoneNumber}
           href="tel: +16044484856">(604) 435 - 5353</a>

       <section className={styles.stores_buttons}>
        <Link href="https://www.medicineshoppe.ca/en/find-a-store?ID=SEM&gclid=Cj0KCQjwi46iBhDyARIsAE3nVrZI9JQwrN8s2J5RLPA0oRuI9v8nGYZG_48tlh28rvw7XhF3rWU2oD0aAlqpEALw_wcB&gclsrc=aw.ds/">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/place/The+Medicine+Shoppe+Pharmacy/@49.2499989,-123.1011691,12z/data=!3m1!5s0x548676f49423fc77:0x1ddc939d1f2f4fb3!4m10!1m2!2m1!1sThe+Medicine+Shoppe+Pharmacy!3m6!1s0x548676f422e9fed5:0x4cb0bc5252b40aa3!8m2!3d49.232369!4d-123.0100789!15sChxUaGUgTWVkaWNpbmUgU2hvcHBlIFBoYXJtYWN5IgOIAQFaHiIcdGhlIG1lZGljaW5lIHNob3BwZSBwaGFybWFjeZIBCHBoYXJtYWN5mgEkQ2hkRFNVaE5NRzluUzBWSlEwRm5TVU5YYW1GTVRqRkJSUkFC4AEA!16s%2Fg%2F11btv67m_8">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    </section>

        </>
    )}

   
   </main>
   <div className={styles.navbar}>
   <Navbar/>
   </div>
   </div>
    </>

    
    )
}