import styles from '../styles/Store.module.css'
import Link from 'next/link'
import Navbar from '../components/navbar/index.js';
import Head from 'next/head'
import Image from 'next/image';
import { useState } from 'react';


export default function Store() {

const [location, setLocation] = useState (false);
const [inputValue, setInputValue] = useState('');
const locationClicked = () => {
        setLocation(!location);
};

    return (
    <>
    <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
 

<div className={styles.body_main}>
    <main className={styles.main}>

    <Image
           onClick={() => setLocation(true)}
           src = "/icons/overlayButton.png"
           alt =""
           width = {60}
           height = {60}
           />

    <h1>Hello,</h1>
    <p className={styles.store_page_description}>Your medication can be access through these stores:</p>
    
    <div className={styles.store_page_location}>

     <img className={styles.location_picture} src="/icons/location.png" onClick={() => {
        if(location){
                setInputValue("");
        }else{
                setInputValue("3700 Willingdon Avenue Burnaby, BC V5G 3H2");
        }
        locationClicked();
     }}/>

     <input className={styles.store_page_input} type="text" value={inputValue} onChange={(a) => setInputValue(a.target.value)}/>
    </div>

    <div className={styles.store_lists}>

    <section  className={styles.store1}>
        <h1 className={styles.store1_name}>London Drugs</h1>
         
        <p className={styles.store1_adress}>4970 Kingsway Avenue</p>
        <p className={styles.store1_adress}>Burnaby, British Columbia V5H 2E2</p>

        <a className={styles.stores_phoneNumber}
        href="tel: +16044484806">(604) 448 - 4806</a>

<section className={styles.stores_buttons}>
        <Link href="/ChooseSymptoms">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/dir/49.2488105,-122.9805138/4970+Kingsway,+Burnaby,+BC+V5H+2E2/@49.2402446,-123.0058915,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5486765a4154fb4b:0x34d616bf47efd802!2m2!1d-122.9932581!2d49.226">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    <section  className={styles.store1}>
        <h1 className={styles.store1_name}>London Drugs</h1>
         
        <p className={styles.store1_adress}>4970 Kingsway Avenue</p>
        <p className={styles.store1_adress}>Burnaby, British Columbia V5H 2E2</p>

        <a className={styles.stores_phoneNumber}
        href="tel: +16044484806">(604) 448 - 4806</a>

<section className={styles.stores_buttons}>
        <Link href="https://www.londondrugs.com/london-drugs-store-006-burnaby/kingsway-plaza-006.html">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/dir/49.2488105,-122.9805138/4970+Kingsway,+Burnaby,+BC+V5H+2E2/@49.2402446,-123.0058915,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5486765a4154fb4b:0x34d616bf47efd802!2m2!1d-122.9932581!2d49.226">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    <section  className={styles.store1}>
        <h1 className={styles.store1_name}>London Drugs</h1>
         
        <p className={styles.store1_adress}>4970 Kingsway Avenue</p>
        <p className={styles.store1_adress}>Burnaby, British Columbia V5H 2E2</p>

        <a className={styles.stores_phoneNumber}
        href="tel: +16044484806">(604) 448 - 4806</a>

<section className={styles.stores_buttons}>
        <Link href="https://www.londondrugs.com/london-drugs-store-006-burnaby/kingsway-plaza-006.html">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/dir/49.2488105,-122.9805138/4970+Kingsway,+Burnaby,+BC+V5H+2E2/@49.2402446,-123.0058915,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5486765a4154fb4b:0x34d616bf47efd802!2m2!1d-122.9932581!2d49.226">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    <section  className={styles.store1}>
        <h1 className={styles.store1_name}>London Drugs</h1>
         
        <p className={styles.store1_adress}>4970 Kingsway Avenue</p>
        <p className={styles.store1_adress}>Burnaby, British Columbia V5H 2E2</p>

        <a className={styles.stores_phoneNumber}
        href="tel: +16044484806">(604) 448 - 4806</a>

<section className={styles.stores_buttons}>
        <Link href="https://www.londondrugs.com/london-drugs-store-006-burnaby/kingsway-plaza-006.html">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/dir/49.2488105,-122.9805138/4970+Kingsway,+Burnaby,+BC+V5H+2E2/@49.2402446,-123.0058915,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5486765a4154fb4b:0x34d616bf47efd802!2m2!1d-122.9932581!2d49.226">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    <section  className={styles.store1}>
        <h1 className={styles.store1_name}>London Drugs</h1>
         
        <p className={styles.store1_adress}>4970 Kingsway Avenue</p>
        <p className={styles.store1_adress}>Burnaby, British Columbia V5H 2E2</p>

        <a className={styles.stores_phoneNumber}
        href="tel: +16044484806">(604) 448 - 4806</a>

<section className={styles.stores_buttons}>
        <Link href="https://www.londondrugs.com/london-drugs-store-006-burnaby/kingsway-plaza-006.html">
        <button className={styles.store_button} onclick="">More Info</button>
       </Link>

       <Link href="https://www.google.com/maps/dir/49.2488105,-122.9805138/4970+Kingsway,+Burnaby,+BC+V5H+2E2/@49.2402446,-123.0058915,14z/data=!3m1!4b1!4m9!4m8!1m1!4e1!1m5!1m1!1s0x5486765a4154fb4b:0x34d616bf47efd802!2m2!1d-122.9932581!2d49.226">
        <button className={styles.store_button} onclick="">Get Direction</button>
       </Link>
       </section>

    </section>

    </div>

    <Navbar
   className={styles.navbar} />
   </main>
   </div>
    </>

    
    )
}