import styles from '../styles/Symptoms.module.css'
import Head from 'next/head'

export default function Symptoms() {
    return (
    <>

      <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>

      <div className={styles.body_main}>
   
    <h1>Hello You currently have these Symptoms</h1>


    </div>
    </>
    )
}