import Head from 'next/head'
import styles from '../styles/Symptoms.module.css'
import Navbar from '../components/navbar/index.js';
import Topbar from '../components/topbar';
import { useRouter } from 'next/router';
import Category from './Category';



export default function symptomsHead() {

  const router = useRouter();
  const { selectedData } = router.query;

  if (!selectedData) {
    return <Category/>; 
  }

  const data = JSON.parse(selectedData);

  const handleFormSubmit = (event) => {
    event.preventDefault();
    router.push(data.clickedclicker);
  };

  return (
    <>
      <Head>
        <title> Meddy </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/Icon.svg" />
      </Head>
      <div className={styles.body_main}>
        <main className={styles.main}>
        <div className={styles.overlayButton}>
        <Topbar/>
        </div>
       <h1 className={styles.enter_header}>Hello,</h1>
       <h2 className={styles.label}>Where do you feel discomfort</h2>
       <div>
          <div className={styles.title_header}>
            <h3>{data.category}</h3>
            <h4>{data.description}</h4>
          </div>
          <div className={styles.infoButtons}>
              <div className={styles.input_name} >
                <input type="checkbox"></input>
                <p>{data.symptomsOne}</p>
              </div>
              <div className={styles.input_name} >
                <input type="checkbox"></input>
                <p>{data.symptomsTwo}</p>
              </div>
              <div className={styles.input_name} >
                <input type="checkbox"></input>
                <p>{data.symptomsThree}</p>
              </div>
              <div className={styles.input_name} >
                <input type="checkbox"></input>
                <p>{data.symptomsFour}</p>
              </div>
          </div>
      </div>

      <form onSubmit={handleFormSubmit}>
        <div className={styles.enteryourpage_submit_button_div}>
          <button type="submit" className={styles.enteryourpage_submit_button}>Submit</button>
        </div>
      </form>
    </main>
      <div className={styles.navbar}>
      <Navbar/>
      </div>
      </div>
    </>
  );
}
